version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python3 main.py
    volumes:
      - ./src/data:/src/data
      - ./src/logs:/src/logs
      - ./src/mail:/src/mail
      # - ./SpeedtestAutomation:/src
